### PR TITLE
Fix environment and error tag

### LINKED ISSUE #74: error tag has been correct set, but the dashboard still show 0 errors
The `error` tag has been correct set (https://github.com/opentracing-contrib/nginx-opentracing/blob/master/opentracing/src/opentracing_context.cpp#L66) but in APM-UI its doesn't count 5xx as error.

This is the screen of service:
screen shot 2018-12-10 at 2 59 17 pm
This is the detail of data for that trace:
screen shot 2018-12-10 at 3 01 49 pm

### PR DESCRIPTION
**Pull request by wanx0007**
Change the environment tag from "environment" to "env".
"env" is what's specified in the documentation.

Fixes #74

### CODE REVIEW

File: src/span.cpp [hunk 1]
```diff
@@ -145,6 +145,11 @@ void Span::FinishWithOptions(
     span_->service = tag->second;
     span_->meta.erase(tag);
   }
+  tag = span_->meta.find("error");
```
Comment (willgittoes-dd) [inline src/span.cpp]:
```suggestion
  tag = span_->meta.find(datadog_error_tag);
```

File: src/span.cpp [hunk 2]
```diff
@@ -22,7 +22,7 @@ const std::string http_url_tag = "http.url";
 const std::string operation_name_tag = "operation";
```
Comment (willgittoes-dd) [inline src/span.cpp]:
```suggestion
const std::string datadog_error_tag = "error";
const std::string operation_name_tag = "operation";
```
